# -*- coding: utf-8 -*-
"""Energy_Tracker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RRtYfOLTgXDQWKR_Xl6vb_q1XbjiqTYW
"""

import streamlit as st

# Appliance data: name and estimated watts/hour
appliance_usage = {
    "TV": 100,
    "Fridge": 150,
    "Washing Machine": 500,
    "Air Conditioner": 1000,
    "Microwave": 800
}

# Main function
def main():
    st.title("🔌 Smart Energy Consumption Tracker")

    st.header("User Details")
    name = st.text_input("Name")
    age = st.number_input("Age", min_value=1, step=1)
    area = st.text_input("Area")
    city = st.text_input("City")

    st.selectbox("Type of House", ["Flat", "Tenament"], key="house_type")
    bhk = st.number_input("Number of BHK", min_value=1, step=1)

    st.header("Select Appliances You Use")
    selected_appliances = st.multiselect(
        "Choose appliances", options=list(appliance_usage.keys())
    )

    if st.button("Calculate Energy Consumption"):
        if not name or not area or not city or not selected_appliances:
            st.warning("Please fill all details and select at least one appliance.")
        else:
            total_watts = sum(appliance_usage[app] for app in selected_appliances)
            estimated_units = (total_watts * 5 * 30) / 1000  # 5 hours/day * 30 days

            st.subheader("📊 Estimated Energy Consumption")
            st.markdown(f"**Name:** {name}")
            st.markdown(f"**Age:** {age}")
            st.markdown(f"**Location:** {area}, {city}")
            st.markdown(f"**House Type:** {st.session_state.house_type} ({bhk} BHK)")
            st.markdown(f"**Appliances Selected:** {', '.join(selected_appliances)}")
            st.success(f"⚡ Estimated Monthly Energy Consumption: {estimated_units:.2f} kWh")


if __name__ == "__main__":
    main()