# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JLjuU3fcjxLLeIu790RyL13teG2OWAOf
"""

import streamlit as st
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_squared_error, r2_score, classification_report, accuracy_score, confusion_matrix
import plotly.express as px
import plotly.graph_objects as go

# Set page config
st.set_page_config(
    page_title="Solar Panel Performance Forecasting",
    page_icon="☀️",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Title and description
st.title("☀️ Solar Panel Performance Forecasting")
st.markdown("**Predict solar panel energy output across different seasons using machine learning**")

# Sidebar for navigation
st.sidebar.title("Navigation")
page = st.sidebar.selectbox(
    "Choose a page:",
    ["Data Generation", "Data Visualization", "Regression Model", "Classification Model", "Prediction Tool"]
)

# Data generation functions
@st.cache_data
def generate_seasonal_data():
    """Generate synthetic solar panel data for all seasons"""

    # Feature ranges for each season
    feature_ranges = {
        'summer': {
            'irradiance': (600, 1000),
            'humidity': (10, 50),
            'wind_speed': (0, 5),
            'ambient_temperature': (30, 45),
            'tilt_angle': (10, 40),
        },
        'winter': {
            'irradiance': (300, 700),
            'humidity': (30, 70),
            'wind_speed': (1, 6),
            'ambient_temperature': (5, 20),
            'tilt_angle': (10, 40),
        },
        'monsoon': {
            'irradiance': (100, 600),
            'humidity': (70, 100),
            'wind_speed': (2, 8),
            'ambient_temperature': (20, 35),
            'tilt_angle': (10, 40),
        }
    }

    # Months and days for each season
    season_months = {
        'summer': {'March': 31, 'April': 30, 'May': 31, 'June': 30},
        'winter': {'November': 30, 'December': 31, 'January': 31, 'February': 28},
        'monsoon': {'July': 31, 'August': 31, 'September': 30, 'October': 31}
    }

    # KWh calculation functions
    def calc_kwh_summer(irradiance, humidity, wind_speed, ambient_temp, tilt_angle):
        return (0.25 * irradiance - 0.05 * humidity + 0.02 * wind_speed +
                0.1 * ambient_temp - 0.03 * abs(tilt_angle - 30))

    def calc_kwh_winter(irradiance, humidity, wind_speed, ambient_temp, tilt_angle):
        return (0.18 * irradiance - 0.03 * humidity + 0.015 * wind_speed +
                0.08 * ambient_temp - 0.02 * abs(tilt_angle - 30))

    def calc_kwh_monsoon(irradiance, humidity, wind_speed, ambient_temp, tilt_angle):
        return (0.15 * irradiance - 0.1 * humidity + 0.01 * wind_speed +
                0.05 * ambient_temp - 0.04 * abs(tilt_angle - 30))

    calc_functions = {
        'summer': calc_kwh_summer,
        'winter': calc_kwh_winter,
        'monsoon': calc_kwh_monsoon
    }

    all_data = []

    for season in ['summer', 'winter', 'monsoon']:
        for month, days in season_months[season].items():
            for _ in range(days):
                irr = np.random.uniform(*feature_ranges[season]['irradiance'])
                hum = np.random.uniform(*feature_ranges[season]['humidity'])
                wind = np.random.uniform(*feature_ranges[season]['wind_speed'])
                temp = np.random.uniform(*feature_ranges[season]['ambient_temperature'])
                tilt = np.random.uniform(*feature_ranges[season]['tilt_angle'])

                kwh = calc_functions[season](irr, hum, wind, temp, tilt)

                all_data.append({
                    'irradiance': round(irr, 2),
                    'humidity': round(hum, 2),
                    'wind_speed': round(wind, 2),
                    'ambient_temperature': round(temp, 2),
                    'tilt_angle': round(tilt, 2),
                    'kwh': round(kwh, 2),
                    'season': season,
                    'month': month
                })

    return pd.DataFrame(all_data)

# Generate the data
df = generate_seasonal_data()

# PAGE 1: Data Generation
if page == "Data Generation":
    st.header("📊 Data Generation")

    col1, col2 = st.columns(2)

    with col1:
        st.subheader("Dataset Overview")
        st.write(f"**Total Records:** {len(df)}")
        st.write(f"**Features:** {df.shape[1] - 2}")  # Excluding season and month
        st.write(f"**Seasons:** {df['season'].nunique()}")

        # Season distribution
        season_counts = df['season'].value_counts()
        st.write("**Records per Season:**")
        for season, count in season_counts.items():
            st.write(f"- {season.title()}: {count} days")

    with col2:
        st.subheader("Sample Data")
        st.dataframe(df.head(10))

    st.subheader("Dataset Statistics")
    st.dataframe(df.describe())

    # Download button
    csv = df.to_csv(index=False)
    st.download_button(
        label="📥 Download Dataset as CSV",
        data=csv,
        file_name='solar_performance_data.csv',
        mime='text/csv'
    )

# PAGE 2: Data Visualization
elif page == "Data Visualization":
    st.header("📈 Data Visualization")

    # KWh by Season Box Plot
    st.subheader("Energy Output Distribution by Season")
    fig_box = px.box(df, x='season', y='kwh',
                     title='Solar Panel Energy Output (kWh) by Season',
                     color='season')
    st.plotly_chart(fig_box, use_container_width=True)

    # Daily Energy Output
    st.subheader("Day-wise Energy Output")
    fig_daily = px.bar(df, x=df.index, y='kwh',
                       title='Day-wise Solar Panel Energy Output',
                       color='season')
    st.plotly_chart(fig_daily, use_container_width=True)

    # Correlation Heatmap
    st.subheader("Feature Correlation Matrix")
    numeric_cols = ['irradiance', 'humidity', 'wind_speed', 'ambient_temperature', 'tilt_angle', 'kwh']
    corr_matrix = df[numeric_cols].corr()

    fig_heatmap = px.imshow(corr_matrix,
                           title='Feature Correlation Matrix',
                           color_continuous_scale='RdBu',
                           aspect="auto")
    st.plotly_chart(fig_heatmap, use_container_width=True)

    # Feature distributions
    st.subheader("Feature Distributions by Season")
    feature_to_plot = st.selectbox("Select feature:", numeric_cols[:-1])

    fig_dist = px.histogram(df, x=feature_to_plot, color='season',
                           title=f'{feature_to_plot.title()} Distribution by Season',
                           marginal='box')
    st.plotly_chart(fig_dist, use_container_width=True)

# PAGE 3: Regression Model
elif page == "Regression Model":
    st.header("🔮 Regression Model - Predicting Energy Output")

    # Prepare data
    X = df[['irradiance', 'humidity', 'wind_speed', 'ambient_temperature', 'tilt_angle']]
    y = df['kwh']

    # Model parameters
    st.sidebar.subheader("Model Parameters")
    test_size = st.sidebar.slider("Test Size", 0.1, 0.4, 0.2)
    random_state = st.sidebar.number_input("Random State", 0, 100, 42)

    # Train model
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=random_state)

    model = LinearRegression()
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    # Metrics
    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)

    col1, col2 = st.columns(2)

    with col1:
        st.subheader("Model Performance")
        st.metric("R² Score", f"{r2:.4f}")
        st.metric("Mean Squared Error", f"{mse:.4f}")
        st.metric("RMSE", f"{np.sqrt(mse):.4f}")

        st.subheader("Model Coefficients")
        coef_df = pd.DataFrame({
            'Feature': X.columns,
            'Coefficient': model.coef_,
            'Abs_Coefficient': np.abs(model.coef_)
        }).sort_values('Abs_Coefficient', ascending=False)

        st.dataframe(coef_df)
        st.write(f"**Intercept:** {model.intercept_:.4f}")

    with col2:
        st.subheader("Actual vs Predicted")

        # Create scatter plot
        fig_scatter = go.Figure()

        # Add scatter points
        fig_scatter.add_trace(go.Scatter(
            x=y_test, y=y_pred,
            mode='markers',
            name='Predictions',
            marker=dict(color='blue', size=8, opacity=0.6)
        ))

        # Add diagonal line
        min_val = min(y_test.min(), y_pred.min())
        max_val = max(y_test.max(), y_pred.max())
        fig_scatter.add_trace(go.Scatter(
            x=[min_val, max_val], y=[min_val, max_val],
            mode='lines',
            name='Perfect Prediction',
            line=dict(color='red', dash='dash')
        ))

        fig_scatter.update_layout(
            title='Actual vs Predicted kWh',
            xaxis_title='Actual kWh',
            yaxis_title='Predicted kWh',
            showlegend=True
        )

        st.plotly_chart(fig_scatter, use_container_width=True)

    # Feature importance
    st.subheader("Feature Importance")
    fig_importance = px.bar(coef_df, x='Feature', y='Abs_Coefficient',
                           title='Feature Importance (Absolute Coefficients)')
    st.plotly_chart(fig_importance, use_container_width=True)

# PAGE 4: Classification Model
elif page == "Classification Model":
    st.header("🏷️ Classification Model - Predicting Season")

    # Prepare data
    X = df[['irradiance', 'humidity', 'wind_speed', 'ambient_temperature', 'tilt_angle', 'kwh']]
    y = df['season']

    # Encode target
    le = LabelEncoder()
    y_encoded = le.fit_transform(y)

    # Model parameters
    st.sidebar.subheader("Model Parameters")
    test_size = st.sidebar.slider("Test Size", 0.1, 0.4, 0.2, key="class_test_size")
    random_state = st.sidebar.number_input("Random State", 0, 100, 42, key="class_random_state")
    max_iter = st.sidebar.slider("Max Iterations", 100, 1000, 200)

    # Train model
    X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=test_size, random_state=random_state)

    model = LogisticRegression(max_iter=max_iter)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    # Metrics
    accuracy = accuracy_score(y_test, y_pred)

    col1, col2 = st.columns(2)

    with col1:
        st.subheader("Model Performance")
        st.metric("Accuracy", f"{accuracy:.4f}")

        st.subheader("Classification Report")
        report = classification_report(y_test, y_pred, target_names=le.classes_, output_dict=True)
        report_df = pd.DataFrame(report).transpose()
        st.dataframe(report_df.round(4))

    with col2:
        st.subheader("Confusion Matrix")
        cm = confusion_matrix(y_test, y_pred)

        fig_cm = px.imshow(cm,
                          text_auto=True,
                          aspect="auto",
                          title='Confusion Matrix',
                          labels=dict(x="Predicted", y="Actual"),
                          x=le.classes_,
                          y=le.classes_)
        st.plotly_chart(fig_cm, use_container_width=True)

    # Prediction probabilities
    st.subheader("Prediction Probabilities (First 10 Test Samples)")
    y_prob = model.predict_proba(X_test)
    prob_df = pd.DataFrame(y_prob, columns=le.classes_)
    prob_df['Actual'] = le.inverse_transform(y_test)
    prob_df['Predicted'] = le.inverse_transform(y_pred)
    st.dataframe(prob_df.head(10).round(4))

# PAGE 5: Prediction Tool
elif page == "Prediction Tool":
    st.header("🔧 Interactive Prediction Tool")

    # Train models for predictions
    X = df[['irradiance', 'humidity', 'wind_speed', 'ambient_temperature', 'tilt_angle']]
    y_kwh = df['kwh']
    y_season = df['season']

    # Regression model
    reg_model = LinearRegression()
    reg_model.fit(X, y_kwh)

    # Classification model
    le = LabelEncoder()
    y_season_encoded = le.fit_transform(y_season)
    X_class = df[['irradiance', 'humidity', 'wind_speed', 'ambient_temperature', 'tilt_angle', 'kwh']]
    class_model = LogisticRegression(max_iter=200)
    class_model.fit(X_class, y_season_encoded)

    st.subheader("Enter Solar Panel Conditions")

    col1, col2 = st.columns(2)

    with col1:
        irradiance = st.slider("Solar Irradiance (W/m²)", 100, 1000, 600)
        humidity = st.slider("Humidity (%)", 10, 100, 50)
        wind_speed = st.slider("Wind Speed (m/s)", 0.0, 10.0, 3.0)

    with col2:
        ambient_temp = st.slider("Ambient Temperature (°C)", 5, 45, 25)
        tilt_angle = st.slider("Panel Tilt Angle (degrees)", 10, 40, 30)

    if st.button("🔮 Make Predictions"):
        # Prepare input
        input_features = np.array([[irradiance, humidity, wind_speed, ambient_temp, tilt_angle]])

        # Energy prediction
        predicted_kwh = reg_model.predict(input_features)[0]

        # Season prediction
        input_features_season = np.array([[irradiance, humidity, wind_speed, ambient_temp, tilt_angle, predicted_kwh]])
        predicted_season_prob = class_model.predict_proba(input_features_season)[0]
        predicted_season = le.inverse_transform(class_model.predict(input_features_season))[0]

        # Display results
        st.success("✅ Predictions Generated!")

        col1, col2 = st.columns(2)

        with col1:
            st.subheader("Energy Output Prediction")
            st.metric("Predicted kWh", f"{predicted_kwh:.2f}")

            # Compare with season averages
            season_avg = df.groupby('season')['kwh'].mean()
            st.write("**Comparison with Season Averages:**")
            for season, avg in season_avg.items():
                diff = predicted_kwh - avg
                st.write(f"- {season.title()}: {avg:.2f} kWh (diff: {diff:+.2f})")

        with col2:
            st.subheader("Season Classification")
            st.write(f"**Most Likely Season:** {predicted_season.title()}")

            # Show probabilities
            st.write("**Season Probabilities:**")
            for i, season in enumerate(le.classes_):
                prob = predicted_season_prob[i]
                st.write(f"- {season.title()}: {prob:.1%}")
                st.progress(prob)

    # Show input summary
    st.subheader("Input Summary")
    input_summary = pd.DataFrame({
        'Parameter': ['Solar Irradiance', 'Humidity', 'Wind Speed', 'Ambient Temperature', 'Tilt Angle'],
        'Value': [f"{irradiance} W/m²", f"{humidity}%", f"{wind_speed} m/s", f"{ambient_temp}°C", f"{tilt_angle}°"],
        'Season Range': [
            f"Summer: 600-1000, Winter: 300-700, Monsoon: 100-600",
            f"Summer: 10-50, Winter: 30-70, Monsoon: 70-100",
            f"Summer: 0-5, Winter: 1-6, Monsoon: 2-8",
            f"Summer: 30-45, Winter: 5-20, Monsoon: 20-35",
            f"All seasons: 10-40"
        ]
    })
    st.dataframe(input_summary, use_container_width=True)

# Footer
st.markdown("---")
st.markdown("**Solar Panel Performance Forecasting Dashboard** | Built with Streamlit")